/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.ContaSalario;
import dao.contaCorrenteDAO;
import dao.contaSalarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class formPagamentoSalario extends javax.swing.JFrame {
    
    private int idUsuarioSelecionado = -1;
    private int idUsuarioLogado;
    private formTransf telaTransferencia;
    private formContaCorrente telaContaCorrente;
    private contaCorrenteDAO contaCorrenteDAO = new contaCorrenteDAO();
    
    /**
     * Creates new form formPagamentoSalario
     */
    public formPagamentoSalario() {
        initComponents();
        
        carregarUsuariosContaSalario();
    }
    
    public void carregarUsuariosContaSalario() {
    try {
        contaSalarioDAO dao = new contaSalarioDAO();
        List<ContaSalario> lista = dao.listarUsuariosContaSalario();

        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0); 

        for (ContaSalario cs : lista) {
            modelo.addRow(new Object[]{
                cs.getId(),
                cs.getNome(),
                cs.getEmpresaContratante()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar usuários: " + e.getMessage());
    }
}
    
    public void setIdUsuarioLogado(int id) {
    this.idUsuarioLogado = id;
    carregarSaldo();
}
    
    public void setTelaContaCorrente(formContaCorrente tela) {
    this.telaContaCorrente = tela;
}


    
    public void carregarSaldo() {
    try {
        contaCorrenteDAO dao = new contaCorrenteDAO();
        double saldo = dao.buscarSaldoPorIdUsuario(idUsuarioLogado);
        txtSaldoPagamento.setText(String.valueOf(saldo));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar saldo: " + e.getMessage());
    }
}


    

    public void setTelaTransferencia(formTransf tela) {
    this.telaTransferencia = tela;
    }

    

        private void tabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {
    int linhaSelecionada = tblUsuarios.getSelectedRow();
    if (linhaSelecionada != -1) {
        idUsuarioSelecionado = (int) tblUsuarios.getValueAt(linhaSelecionada, 0);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtSaldoPagamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtValorPagamento = new javax.swing.JTextField();
        btnPagarSalario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento Salario");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Banco ByteBank");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel2.setText("Valor do Pagamento:");

        txtSaldoPagamento.setEditable(false);
        txtSaldoPagamento.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtSaldoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoPagamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Pagamento Salario");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Empresa"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel4.setText("Saldo Disponivel:");

        txtValorPagamento.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N

        btnPagarSalario.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnPagarSalario.setText("Pagar");
        btnPagarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarSalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSaldoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addComponent(jSeparator2)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(btnPagarSalario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addComponent(jLabel4)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSaldoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnPagarSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jLabel4)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoPagamentoActionPerformed

    private void btnPagarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarSalarioActionPerformed
        try {
        int linha = tblUsuarios.getSelectedRow();
        if (linha == -1) {
            throw new Exception("Selecione um usuário da tabela.");
        }

        int idUsuario = (int) tblUsuarios.getValueAt(linha, 0);
        String empresa = (String) tblUsuarios.getValueAt(linha, 2); 
        double valor = Double.parseDouble(txtValorPagamento.getText().trim());
        
        

        if (valor <= 0) {
            throw new Exception("Informe um valor válido maior que zero.");
        }

        contaSalarioDAO dao = new contaSalarioDAO();
        dao.realizarPagamentoSalario(empresa, idUsuario, valor);
        contaCorrenteDAO.sacar(idUsuarioLogado, valor);
        carregarSaldo();

        JOptionPane.showMessageDialog(this, "Pagamento realizado com sucesso!");
        txtValorPagamento.setText("");
        
        if (telaTransferencia != null) {
        telaTransferencia.carregarSaldo(idUsuarioLogado);
        }
        if (telaContaCorrente != null) {
        telaContaCorrente.atualizarDadosContaCorrente();
        }


    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Digite um valor numérico válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnPagarSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPagamentoSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPagamentoSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPagamentoSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPagamentoSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPagamentoSalario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagarSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtSaldoPagamento;
    private javax.swing.JTextField txtValorPagamento;
    // End of variables declaration//GEN-END:variables
}
