/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Investimento;
import dao.InvestimentoDAO;
import dao.contaCorrenteDAO;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.sql.Date;


/**
 *
 * @author nicol
 */
public class formInvestimento extends javax.swing.JFrame {
    private int idUsuarioLogado;
    private formContaCorrente telaContaCorrente;
    /**
     * Creates new form formInvestimento
     */
    public formInvestimento() {
        initComponents();
    }

    public void setIdUsuarioLogado(int id) {
    this.idUsuarioLogado = id;
    carregarSaldo(); 
}
    
    public void setTelaContaCorrente(formContaCorrente tela) {
    this.telaContaCorrente = tela;
    }


    
    public void carregarSaldo() {
    try {
        contaCorrenteDAO dao = new contaCorrenteDAO();
        double saldo = dao.buscarSaldoPorIdUsuario(idUsuarioLogado);
        txtSaldoInvestimento.setText(String.format("R$ %.2f", saldo)); 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar saldo: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSaldoInvestimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cmbTempoInvestimento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbTipoInvestimento = new javax.swing.JComboBox<>();
        btnResgateInv = new javax.swing.JButton();
        btnInvestir = new javax.swing.JButton();
        txtValorInvestimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Investimentos");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Banco ByteBank");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel2.setText("Saldo Disponivel:");

        txtSaldoInvestimento.setEditable(false);
        txtSaldoInvestimento.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtSaldoInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoInvestimentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Investimentos");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel5.setText("Insira o valor:");

        cmbTempoInvestimento.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        cmbTempoInvestimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "60", "120", "365" }));
        cmbTempoInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTempoInvestimentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel6.setText("Selecione o investimento:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel7.setText("Tempo:");

        cmbTipoInvestimento.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        cmbTipoInvestimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BTC - Medio", "ETH - Alto", "BNB  - Medio", "XRP - Baixo" }));

        btnResgateInv.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        btnResgateInv.setText("Resgatar");
        btnResgateInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResgateInvActionPerformed(evt);
            }
        });

        btnInvestir.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        btnInvestir.setText("Investir");
        btnInvestir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestirActionPerformed(evt);
            }
        });

        txtValorInvestimento.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTempoInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(195, 195, 195))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldoInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInvestir)
                        .addGap(59, 59, 59)
                        .addComponent(btnResgateInv)
                        .addGap(273, 273, 273))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldoInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cmbTempoInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtValorInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cmbTipoInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResgateInv)
                    .addComponent(btnInvestir))
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoInvestimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoInvestimentoActionPerformed

    private void cmbTempoInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTempoInvestimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTempoInvestimentoActionPerformed

    private void btnResgateInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResgateInvActionPerformed
         formResgateInvestimento telaResgate = new formResgateInvestimento();
         telaResgate.setIdUsuarioLogado(idUsuarioLogado);
         telaResgate.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnResgateInvActionPerformed

    private void btnInvestirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvestirActionPerformed
        try {
        String tipo = cmbTipoInvestimento.getSelectedItem().toString();
        int duracao = Integer.parseInt(cmbTempoInvestimento.getSelectedItem().toString());
        double valor = Double.parseDouble(txtValorInvestimento.getText());

        Investimento inv = new Investimento();
        inv.setIdUsuario(idUsuarioLogado);
        inv.setTipo(tipo);
        inv.setValor(valor);
        inv.setDuracaoDias(duracao);
        inv.setDataInicio(Date.valueOf(LocalDate.now()));
        inv.setStatus("ativo");

        InvestimentoDAO dao = new InvestimentoDAO();
        dao.inserirInvestimento(inv);

        JOptionPane.showMessageDialog(this, "Investimento registrado com sucesso!");
        
        carregarSaldo(); 

        if (telaContaCorrente != null) {
        telaContaCorrente.atualizarDadosContaCorrente();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao registrar investimento: " + e.getMessage());
    }
    }//GEN-LAST:event_btnInvestirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formInvestimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvestir;
    private javax.swing.JButton btnResgateInv;
    private javax.swing.JComboBox<String> cmbTempoInvestimento;
    private javax.swing.JComboBox<String> cmbTipoInvestimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtSaldoInvestimento;
    private javax.swing.JTextField txtValorInvestimento;
    // End of variables declaration//GEN-END:variables
}
