/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Conta;
import dao.contaCorrenteDAO;
import dao.contaDAO;
import dao.contaSalarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class formLogin extends javax.swing.JFrame {

    private contaDAO ContaDAO;
    
    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
        this.ContaDAO = new contaDAO();
    }

    private void limparCampos() {
        txtNome.setText("");
        txtSenha.setText("");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipoConta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        cmbTipoContaLog = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        cmbTipoConta.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        cmbTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta corrente", "Conta Salario" }));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel3.setText("Tipo de conta:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Banco ByteBank");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel2.setText("Senha:");

        Nome.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Nome.setText("Nome:");

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N

        txtNome.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N

        btnEntrar.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        cmbTipoContaLog.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        cmbTipoContaLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta corrente", "Conta Salario" }));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel4.setText("Tipo de conta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoContaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEntrar)
                        .addGap(333, 333, 333))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cmbTipoContaLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnEntrar)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
    String nome = txtNome.getText().trim();
    String senha = new String(txtSenha.getPassword()).trim();
    String tipoContaSelecionada = cmbTipoContaLog.getSelectedItem().toString();

    if (nome.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        return;
    }

    Conta c = new Conta();
    c.setNome(nome);
    c.setSenha(senha);

    try {
        Conta contaLogada = this.ContaDAO.login(c);

        if (tipoContaSelecionada.equals("Conta corrente")) {
            
            contaCorrenteDAO daoCC = new contaCorrenteDAO();
            boolean existe = daoCC.verificarContaCorrentePorId(contaLogada.getId());

            if (!existe) {
                throw new Exception("Este usuário não possui conta corrente.");
            }

            formContaCorrente tela = new formContaCorrente();
            tela.setIdUsuarioLogado(contaLogada.getId());
            tela.carregarDadosUsuario(contaLogada.getId());
            tela.setVisible(true);
            this.dispose();
            
        } else if (tipoContaSelecionada.equals("Conta Salario")) {
            contaSalarioDAO daoSalario = new contaSalarioDAO();
            boolean existe = daoSalario.verificarContaSalarioPorId(contaLogada.getId());

            if (!existe) {
                throw new Exception("Este usuário não possui conta salário.");
            }

            formContaSalario tela = new formContaSalario();
            tela.setIdUsuarioLogadoSalario(contaLogada.getId());
            tela.carregarDadosUsuarioSalario(contaLogada.getId());
            tela.setVisible(true);
            this.dispose();
        } else {
            throw new Exception("Tipo de conta inválido.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Login", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox<String> cmbTipoConta;
    private javax.swing.JComboBox<String> cmbTipoContaLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
