/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Conta;
import beans.HistoricoTransacao;
import dao.HistoricoDAO;
import dao.contaCorrenteDAO;
import dao.contaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class formSaque extends javax.swing.JFrame {
    private int idUsuarioLogado;
    private formContaCorrente telaContaCorrente;
    private contaCorrenteDAO contaCorrenteDAO = new contaCorrenteDAO();
    private contaDAO contaDAO = new contaDAO();

    /**
     * Creates new form formBanco
     */
    public formSaque() {
        initComponents();
        carregarHistorico();
        
    }

    public void setIdUsuarioLogado(int id) {
    this.idUsuarioLogado = id;
    carregarSaldo();
    }
    
    public void carregarSaldo() {
    try {
        double saldo = contaCorrenteDAO.buscarSaldoPorIdUsuario(idUsuarioLogado);
        txtSaldoSaque.setText(String.format("R$ %.2f", saldo));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar saldo: " + e.getMessage());
    }
}
    public void setTelaContaCorrente(formContaCorrente tela) {
    this.telaContaCorrente = tela;
}
    
    public void carregarHistorico() {
    try {
        HistoricoDAO dao = new HistoricoDAO();
        List<HistoricoTransacao> lista = dao.listarTransacoesPorTipo("Saque");

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        for (HistoricoTransacao t : lista) {
        modelo.addRow(new Object[]{
        t.getNomePagante(),
        t.getTipo(),
        String.format("R$ %.2f", t.getValor()),
        t.getDataTransacao().toLocalDateTime()
    });
}

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar histórico: " + e.getMessage());
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtSaldoSaque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorSaque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtConfSenhaSacar = new javax.swing.JPasswordField();
        txtSenhaSacar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saque");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Banco ByteBank");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel2.setText("Saldo Disponivel:");

        txtSaldoSaque.setEditable(false);
        txtSaldoSaque.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtSaldoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoSaqueActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Saque");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel4.setText("Valor a sacar:");

        txtValorSaque.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel5.setText("Insira sua senha:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel6.setText("Confirme sua senha:");

        btnSacar.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sacador", "Tipo", "Valor", "Data da transação"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtConfSenhaSacar.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N

        txtSenhaSacar.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtSenhaSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaSacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenhaSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfSenhaSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 440, Short.MAX_VALUE)
                        .addComponent(btnSacar)
                        .addGap(339, 339, 339))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(372, 372, 372))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSaldoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtConfSenhaSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenhaSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSacar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoSaqueActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        try {
        String senha = txtSenhaSacar.getText().trim();
        String confirmarSenha = txtConfSenhaSacar.getText().trim();
        double valor = Double.parseDouble(txtValorSaque.getText());

        if (senha.isEmpty() || confirmarSenha.isEmpty()) {
            throw new Exception("Preencha os campos de senha.");
        }

        if (!senha.equals(confirmarSenha)) {
            throw new Exception("As senhas não coincidem.");
        }
        
        contaDAO dao = new contaDAO();
        if (!dao.verificarSenha(idUsuarioLogado, senha)) {
            throw new Exception("Senha incorreta.");
        }

        double saldoAtual = contaCorrenteDAO.buscarSaldoPorIdUsuario(idUsuarioLogado);

        if (valor > saldoAtual) {
            throw new Exception("Saldo insuficiente para saque.");
        }

        
        contaCorrenteDAO.sacar(idUsuarioLogado, valor);

        
        HistoricoDAO historicoDAO = new HistoricoDAO();
        historicoDAO.registrarTransacao(idUsuarioLogado, idUsuarioLogado, "Saque", valor);

        carregarSaldo(); 
        carregarHistorico(); 
        txtValorSaque.setText("");

        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");
        
        if (telaContaCorrente != null) {
        telaContaCorrente.atualizarDadosContaCorrente();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void txtSenhaSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaSacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formSaque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField txtConfSenhaSacar;
    private javax.swing.JTextField txtSaldoSaque;
    private javax.swing.JPasswordField txtSenhaSacar;
    private javax.swing.JTextField txtValorSaque;
    // End of variables declaration//GEN-END:variables
}
