/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Investimento;
import dao.InvestimentoDAO;
import dao.contaCorrenteDAO;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class formResgateInvestimento extends javax.swing.JFrame {
    private int idUsuarioLogado;
    private formContaCorrente telaContaCorrente;

    /**
     * Creates new form formResgateInvestimento
     */
    public formResgateInvestimento() {
        initComponents();
    }
    
    public void setIdUsuarioLogado(int id) {
    this.idUsuarioLogado = id;
    carregarSaldo();
    carregarInvestimentosDoUsuario(); 
}


    public void carregarInvestimentosDoUsuario() {
    try {
        InvestimentoDAO dao = new InvestimentoDAO();
        List<Investimento> lista = dao.listarInvestimentosPorUsuario(idUsuarioLogado);

        DefaultTableModel modelo = (DefaultTableModel) tblInvestimentos.getModel();
        modelo.setRowCount(0); 

        for (Investimento inv : lista) {
            double retorno = calcularRetornoComJuros(inv);
            modelo.addRow(new Object[]{
                inv.getId(),
                inv.getTipo(),
                String.format("R$ %.2f", inv.getValor()),
                inv.getDataInicio().toString(),
                inv.getDuracaoDias(),
                inv.getStatus(),
                String.format("R$ %.2f", retorno)
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar investimentos: " + e.getMessage());
    }
}


    
    private double calcularRetornoComJuros(Investimento inv) {
    double taxaMensal;

    switch (inv.getTipo().toUpperCase()) {
        case "BTC": taxaMensal = 0.035; break;
        case "ETH": taxaMensal = 0.05; break;
        case "BNB": taxaMensal = 0.032; break;
        case "XRP": taxaMensal = 0.02; break;
        default: taxaMensal = 0.025; break;
    }

    int meses = inv.getDuracaoDias() / 30;

    return inv.getValor() * Math.pow(1 + taxaMensal, meses);
}




    
    public void carregarSaldo() {
    try {
        contaCorrenteDAO dao = new contaCorrenteDAO();
        double saldo = dao.buscarSaldoPorIdUsuario(idUsuarioLogado);
        txtSaldoResgate.setText(String.format("R$ %.2f", saldo));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar saldo: " + e.getMessage());
    }
}
    
    private double obterRetornoDaLinha(int linha) {
    String valorComSimbolo = tblInvestimentos.getValueAt(linha, 6).toString();
    return Double.parseDouble(valorComSimbolo.replace("R$", "").replace(",", ".").trim());
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtSaldoResgate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvestimentos = new javax.swing.JTable();
        btnIrInvestimentos = new javax.swing.JButton();
        btnResgatar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Banco ByteBank");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Resgate Investimento");

        txtSaldoResgate.setEditable(false);
        txtSaldoResgate.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtSaldoResgate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoResgateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel4.setText("Saldo Disponivel:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel5.setText("Que investimento deseja resgatar?");

        tblInvestimentos.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        tblInvestimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Valor", "Data", "Dias", "Status", "Retorno"
            }
        ));
        jScrollPane1.setViewportView(tblInvestimentos);

        btnIrInvestimentos.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        btnIrInvestimentos.setText("Investir");
        btnIrInvestimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrInvestimentosActionPerformed(evt);
            }
        });

        btnResgatar.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        btnResgatar.setText("Resgatar");
        btnResgatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResgatarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtSaldoResgate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnResgatar)
                        .addGap(59, 59, 59)
                        .addComponent(btnIrInvestimentos)
                        .addGap(258, 258, 258))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoResgate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrInvestimentos)
                    .addComponent(btnResgatar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoResgateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoResgateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoResgateActionPerformed

    private void btnIrInvestimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrInvestimentosActionPerformed
        formInvestimento tela = new formInvestimento();
        tela.setIdUsuarioLogado(this.idUsuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrInvestimentosActionPerformed

    private void btnResgatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResgatarActionPerformed
        int linhaSelecionada = tblInvestimentos.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um investimento para resgatar.");
        return;
    }

    try {
        int idInvestimento = (int) tblInvestimentos.getValueAt(linhaSelecionada, 0);
        double valorRetorno = obterRetornoDaLinha(linhaSelecionada);

        
        contaCorrenteDAO contaDAO = new contaCorrenteDAO();
        contaDAO.depositar(idUsuarioLogado, valorRetorno);

        
        InvestimentoDAO dao = new InvestimentoDAO();
        dao.removerInvestimento(idInvestimento);

        JOptionPane.showMessageDialog(this, String.format("Investimento resgatado! Valor retornado: R$ %.2f", valorRetorno));

        
        carregarInvestimentosDoUsuario();
        carregarSaldo();
        
        if (telaContaCorrente != null) {
        telaContaCorrente.atualizarDadosContaCorrente();
        }
        
        

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao resgatar investimento: " + e.getMessage());
    }
    }//GEN-LAST:event_btnResgatarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formResgateInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formResgateInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formResgateInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formResgateInvestimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formResgateInvestimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrInvestimentos;
    private javax.swing.JButton btnResgatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblInvestimentos;
    private javax.swing.JTextField txtSaldoResgate;
    // End of variables declaration//GEN-END:variables
}
