/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.ContaSalario;
import dao.contaSalarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class formContaSalario extends javax.swing.JFrame {

        private int idUsuarioLogado;
        private contaSalarioDAO contaSalarioDAO = new contaSalarioDAO();

    /**
     * Creates new form formContaSalario
     */
    public formContaSalario() {
        initComponents();
    }
    
    public void setIdUsuarioLogadoSalario(int id) {
    this.idUsuarioLogado = id;
    }
    
   public void atualizarDadosContaSalario() {
    carregarDadosUsuarioSalario(this.idUsuarioLogado);
}

    
    
    public void carregarDadosUsuarioSalario(int idUsuario) {
    try {
        ContaSalario conta = contaSalarioDAO.obterInformacoesContaSalario(idUsuario);

        if (conta != null) {
            txtNomeUsuario.setText(conta.getNome()); 
            txtSaldoDisponivel.setText(String.format("R$ %.2f", conta.getSaldo()));
        } else {
            JOptionPane.showMessageDialog(this, "Conta salário não encontrada.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar dados da conta salário: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefreshCorrente = new javax.swing.JButton();
        txtNomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtSaldoDisponivel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnTransferenciaSalario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRefreshSalario = new javax.swing.JButton();

        btnRefreshCorrente.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnRefreshCorrente.setText("Refresh");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta Salario");

        txtNomeUsuario.setEditable(false);
        txtNomeUsuario.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("Banco ByteBank");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel5.setText("Saldo disponivel:");

        txtSaldoDisponivel.setEditable(false);
        txtSaldoDisponivel.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        txtSaldoDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoDisponivelActionPerformed(evt);
            }
        });

        btnTransferenciaSalario.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnTransferenciaSalario.setText("Transferencia");
        btnTransferenciaSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaSalarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 2, 25)); // NOI18N
        jLabel6.setText("Conta Salario");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        jLabel3.setText("Seja bem vindo(A)");

        btnRefreshSalario.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnRefreshSalario.setText("Refresh");
        btnRefreshSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshSalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTransferenciaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(238, 238, 238))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(254, 254, 254))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshSalario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnTransferenciaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshSalario)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void txtSaldoDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoDisponivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoDisponivelActionPerformed

    private void btnTransferenciaSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaSalarioActionPerformed
         formTransf tela = new formTransf();                    
         tela.setIdUsuarioLogado(this.idUsuarioLogado);    
         tela.setTelaContaSalario(this);
         tela.setVisible(true);   
        
    }//GEN-LAST:event_btnTransferenciaSalarioActionPerformed

    private void btnRefreshSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshSalarioActionPerformed
        atualizarDadosContaSalario();
    }//GEN-LAST:event_btnRefreshSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formContaSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formContaSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formContaSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formContaSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formContaSalario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshCorrente;
    private javax.swing.JButton btnRefreshSalario;
    private javax.swing.JButton btnTransferenciaSalario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSaldoDisponivel;
    // End of variables declaration//GEN-END:variables
}
